// src/components/shared/cover.svelte
<script lang="ts">
    import type { Cover } from '@gql'
    import Image from './image.svelte'

    export let hentai: Cover
    export let empasize = true

    $: ({
        title: { display },
        images: {
            cover: {
                link,
                info: { width, height }
            }
        },
        metadata: { language },
        info: { favorite, amount }
    } = hentai)

    const languageMap = {
        english: 'EN',
        japanese: '日本',
        chinese: '中文'
    }

    const mapLanguage = (language: string) => languageMap[language] || '-'

    const reduceNumber = (number: number) => {
        if (number < 1000) return number

        return `${(number / 1000).toFixed(1)}k`
    }
</script>

<a class="liftable" sveltekit:prefetch href="/h/{hentai.id}">
    <article class="article flex flex-col gap-2 w-full">
        <div class="cover rounded-2xl border dark:border-gray-700 liftable">
            <div class="image overflow-hidden">
                <Image src={link.replace("cover", "1t")} {width} {height} />
            </div>
        </div>

        <header class="flex flex-1 flex-col gap-1 text-gray-400 text-sm w-full">
            <div class="flex flex-row w-full">
                <h5 class="inline-flex items-center flex-1 {empasize ? "text-gray-600 dark:text-gray-400 text-lg font-medium" : "text-base"}">
                    {display}
                </h5>
            </div>

            <div class="flex flex-row justify-between gap-1 md:gap-1.5">
                <p
                    class="flex flex-[5] sm:flex-[4] items-center gap-1 capitalize"
                >
                    <img
                        class="w-3.5 h-3.5"
                        src="/icons/language.svg"
                        alt="Add"
                    />
                    {mapLanguage(language)}
                </p>
                <p class="flex flex-[4] items-center gap-1 capitalize">
                    <img
                        class="w-3.5 h-3.5"
                        src="/icons/book-open.svg"
                        alt="Add"
                    />
                    {amount}
                </p>
                <p class="flex flex-[4] items-center gap-1 capitalize">
                    <img class="w-3.5 h-3.5" src="/icons/heart.svg" alt="Add" />
                    {reduceNumber(favorite)}
                </p>
            </div>
        </header>
    </article>
</a>

<style lang="sass">
    $expo-out: cubic-bezier(.16,1,.3,1)

    .liftable
        & > .article > .cover
            @apply rounded-xl overflow-hidden
            box-shadow: 0
            transition: box-shadow .375s $expo-out, transform .375s $expo-out

        &:hover,
        &:focus
            & > .article > .cover
                @apply transform -translate-y-4
                transform: scale(1.025) translateY(-0.75rem)
                box-shadow: 0 4px 8px rgba(0, 0, 0, .1)
</style>

// src/layouts/reader/components/cover/index.tsx
import Link from 'next/link'

import tw, { combine } from '@tailwind'

import { BookOpen, Edit2, Heart } from 'react-feather'

import { Page } from '@atoms'

import { Bookmark } from './components'
import { twClass as sharedStyle } from './components/styles'

import styles from './cover.module.sass'

import type { ReaderCoverComponent } from './types'

const twClass = {
	content: tw`flex flex-row items-center text-gray-700 dark:text-gray-400 text-lg my-1 font-medium capitalize`
} as const

const ReaderCover: ReaderCoverComponent = ({
	story: {
		id,
		title: { display },
		images: { cover },
		metadata: {
			tags,
			artist: { name: artistName },
			language
		},
		info: { amount, favorite }
	},
	story
}) => (
	<header
		className={tw`relative flex flex-col md:flex-row w-full my-8 md:my-12 px-4 xs:mb-0 xs:my-8 gap-4 md:gap-8`}
	>
		<div
			className={combine(
				tw`flex flex-col justify-center items-center`,
				styles.wrapper
			)}
			style={{
				flex: 5
			}}
		>
			<Page page={cover} className={styles.cover} />
		</div>
		<div
			className={tw`flex flex-col justify-center`}
			style={{
				flex: 6
			}}
		>
			<h3
				className={tw`text-sm text-gray-500 dark:text-gray-400 font-light mb-2`}
			>
				{id}
			</h3>
			<h1
				className={tw`text-3xl text-gray-900 dark:text-gray-300 m-0 mb-2 font-semibold`}
			>
				{display}
			</h1>
			<section className={tw`flex flex-col my-2`}>
				<h5 className={twClass.content}>
					<BookOpen className={sharedStyle.contentIcon} /> {amount}
				</h5>
				<h5 className={twClass.content}>
					<Heart className={sharedStyle.contentIcon} /> {favorite}
				</h5>
				<h5 className={twClass.content}>
					<Edit2 className={sharedStyle.contentIcon} /> {artistName}
				</h5>
				<h5 className={twClass.content}>
					<img
						className={tw`mr-2`}
						src="/icons/language@black.svg"
						alt="Language"
					/>
					{language}
				</h5>
			</section>
			<section className={combine(styles.tags, tw`block my-2`)}>
				{tags.map(({ name }) => (
					<Link href="/search/[keyword]" as={`/search/${name}`}>
						<a
							className={combine(
								styles.tag,
								tw`inline-block text-md text-gray-800 dark:text-gray-300 font-medium capitalize mr-1 mb-1 px-3 py-2 bg-gray-100 dark:bg-gray-700 no-underline rounded-sm`
							)}
						>
							{name}
						</a>
					</Link>
				))}
			</section>
			<section className={tw`flex flex-row w-full mt-2`}>
				<Bookmark story={story} />
			</section>
		</div>
	</header>
)

export default ReaderCover
