// src/lib/atoms/cover.svelte
<script lang="ts">
    import Image from './image.svelte'
    import {
        GlobeIcon,
        BookOpenIcon,
        HeartIcon,
    } from 'svelte-feather-icons'

    import type { NhqlSearchData } from '$lib/gql/nhqlSearch'

    export let hentai: NhqlSearchData
</script>

<a class="cover relative rounded overflow-hidden" href={`/h/${hentai.id}`}>
    <div
        class="detail z-50 absolute flex flex-col justify-end gap-1 w-full h-full text-white text-lg p-3"
    >
        <h4 class="text-xl font-medium">{hentai.title.display}</h4>

        <p class="flex items-center gap-1 capitalize">
            <GlobeIcon size="21" />
            {hentai.metadata.language}
        </p>

        <div class="flex justify-between">
            <p class="flex flex-1 items-center gap-1 capitalize">
                <BookOpenIcon size="21" />
                {hentai.info.amount}
            </p>
            <p class="flex flex-1 items-center gap-1 capitalize">
                <HeartIcon size="21" />
                {!Intl
                    ? hentai.info.favorite
                    : Intl.NumberFormat().format(hentai.info.favorite)}
            </p>
        </div>
    </div>
    <Image
        parentClass="image"
        src={hentai.images.cover.link}
        size={[hentai.images.cover.info.width, hentai.images.cover.info.height]}
    />
</a>

// src/layouts/vertical-preview/cover/index.tsx
import Link from 'next/link'

import { Page } from '@atoms'

import { Heart, BookOpen } from 'react-feather'

import tw from '@tailwind'

import type { VerticalCoverComponent } from './types'

import styles from './cover.module.sass'

const twClass = {
	info: tw`flex flex-row flex-1 items-center text-gray-400 text-md`
} as const

export const VerticalCover: VerticalCoverComponent = ({
	story: {
		id,
		title: { display },
		images: { cover },
		info: { amount = '', favorite = '' }
	}
}) => (
	<Link href="/h/[id]" as={`/h/${id}`}>
		<a
			role="article"
			className={tw`flex flex-col w-full no-underline cursor-pointer`}
		>
			<Page className={styles.page} page={cover} />
			<h2 className={tw`text-lg sm:text-xl text-gray-700 font-semibold mt-4 mb-2`}>
				{display}
			</h2>
			<footer className={tw`flex flex-row justify-between w-full`}>
				<section className={twClass.info}>
					<Heart width={18} className={tw`mr-2`} />
					{favorite.toLocaleString()}
				</section>
				<section className={twClass.info}>
					<BookOpen width={18} className={tw`mr-2`} />
					{amount.toLocaleString()}
				</section>
			</footer>
		</a>
	</Link>
)
