// src/routes/settings/filter/index.svelte
<script lang="ts">
    import settings from '$lib/stores/settings'

    import SettingLayout from '$lib/layouts/settings.svelte'

    import Toggle from '$lib/atoms/toggle.svelte'
    import Textfield from '$lib/atoms/textfield.svelte'
    import Chip from '$lib/atoms/chip.svelte'
    import SettingRow from '$lib/layouts/setting-row.svelte'

    const addFilter = (value: string) => {
        settings.update((v) => ({
            ...v,
            filter: {
                ...v.filter,
                data: [...new Set(v.filter.data).add(value)]
            }
        }))
    }

    const removeFilter = (value: string) => {
        const data = new Set($settings.filter.data)
        data.delete(value)

        settings.update((v) => ({
            ...v,
            filter: {
                ...v.filter,
                data: [...data]
            }
        }))
    }

    $: disabled = !$settings.filter.enable
    $: disabledClass = disabled ? 'opacity-50 pointer-events-none' : ''
</script>

<SettingLayout
    title="Filter"
    label="Remove unwanted tags or keyword from search results."
>
    <SettingRow title="Enable">
        <svelte:fragment slot="label">
            <p>Allow custom filter.</p>
            <p>Disable this will not removed filter you have added.</p>
        </svelte:fragment>
        <Toggle class="mt-10" bind:value={$settings.filter.enable} />
    </SettingRow>

    <article class="flex flex-col w-full gap-4 text-gray-500 {disabledClass}">
        <h3 class="text-2xl font-semibold text-gray-700 dark:text-gray-400">My filters</h3>
        <p>Type down tags you want to filter out from search down here.</p>
        <Textfield
            id="filter"
            name="filter"
            label="My filter"
            placeholder="To exclude"
            onChange={addFilter}
            {disabled}
        />

        <section class="flex gap-1.5 flex-wrap w-full">
            {#each $settings.filter.data as filter}
                <Chip value={filter} onRemove={removeFilter} {disabled} />
            {/each}
        </section>
    </article>
</SettingLayout>

// src/pages/settings/filter.tsx
import { useRef, useCallback } from 'react'
import type { FormEvent } from 'react'

import { useSettings } from '@stores/settings'

import { SettingLayout, SwitchSetting, SettingLabels } from '@layouts/settings'

import { Plus } from 'react-feather'
import { TextBox, Chip } from '@atoms'

import tw from '@tailwind'

const FilterSetting = () => {
	let {
		settings: { useDefaultFilter, filterList },
		updateSwitch,
		updateSetting
	} = useSettings()

	let filterRef = useRef<HTMLInputElement>(null)

	let addFilter = useCallback(
		(filter: string) => {
			if (!filterList.includes(filter))
				updateSetting('filterList')([...filterList, filter])
		},
		[filterList]
	)

	let removeFilter = useCallback(
		(filter: string) => {
			let newFilter = [...filterList]

			let filterIndex = newFilter.indexOf(filter)

			if (filterIndex === -1) return

			newFilter.splice(filterIndex, 1)

			updateSetting('filterList')(newFilter)
		},
		[filterList]
	)

	let requestAddingFilter = useCallback(
		(event: FormEvent) => {
			event.preventDefault()

			let input = filterRef.current
			if (!input || !input.value) return

			addFilter(input.value)

			input.value = ''
		},
		[filterList]
	)

	return (
		<SettingLayout
			title="Filter"
			labels={['Remove unwanted tags or keyword from your discover.']}
		>
			<SwitchSetting
				value={useDefaultFilter}
				update={updateSwitch('useDefaultFilter')}
			>
				<SettingLabels title="Use default filter" />
			</SwitchSetting>
			<section
				className={tw(
					`flex flex-col w-full transition-opacity ${
						useDefaultFilter
							? 'opacity-50 pointer-events-none cursor-not-allowed'
							: ''
					}`
				)}
			>
				<form
					className={tw`w-2/4 m-0 p-0`}
					onSubmit={requestAddingFilter}
				>
					<TextBox
						inputRef={filterRef}
						name="setting-filter"
						placeholder="Your filter"
						suffix={<Plus />}
					/>
				</form>
				<section className={tw`flex-row flex-nowrap w-full my-2`}>
					{filterList.map((tag) => (
						<Chip
							key={tag}
							className={tw`mr-1 mb-1`}
							value={tag}
							removable
							onRemove={removeFilter}
						/>
					))}
				</section>
			</section>
		</SettingLayout>
	)
}

export default FilterSetting
